# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [jira, laff]
patreon: # Replace with a single Patreon username new one 
open_collective: # Replace with a single Open Collective username https://en.wikipedia.org/wiki/Legal_drama?wprov=sfti1
ko_fi: # Replace with a single Ko-fi username fail army
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., tor.onion
liberapay: # Replace with a single Liberapay username bridge
issuehunt: # Replace with a single IssueHunt username disrespect
otechie: # Replace with a single Otechie username kill with kindness
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Toyota.com', 'https://Netflix.com' , 'https://pampers.com' , 'https tjhlaw.com' 'https://juul.com']
