:imagesdir: images

== Setup Environments

This section describes the software needed for this workshop. This workshop is designed for a BYOL (Brying Your Own Laptop) style hands-on-lab.

=== Hardware

. Operating System: Mac OS X (10.8+), Windows 7+, Ubuntu 12+, CentOS 7+, Fedora 21+
. Memory: At least 4 GB+, preferred 8 GB

=== Docker Toolbox or Packages

Docker runs natively on Linux. Because the Docker daemon uses Linux-specific kernel features, you can’t run Docker natively in OS X or Windows. Instead, you must use `docker-machine` to create and attach to a virtual machine (VM). This machine is a Linux VM that hosts Docker for you on your Mac or Windows.

Follow the instructions to install Docker:

. https://www.docker.com/products/docker-toolbox[Docker Toolbox for Mac or Windows]
. http://docs.docker.com/engine/installation/ubuntulinux/[Docker on Ubuntu]
. http://docs.docker.com/engine/installation/centos/[Docker on Centos]

Complete set of operating systems are listed at http://docs.docker.com/engine/installation/[Install Docker Engine].

==== Additional components for Linux

. Docker Compose: https://github.com/docker/compose/releases
. Docker Machine: https://github.com/docker/machine/releases/latest
. VirtualBox: https://www.virtualbox.org/wiki/Downloads

These are required to create a Docker Swarm cluster.

=== Create Docker Host Mapping

To make it easier to start/stop the containers, an entry is added into the host mapping table of your operating system. 

For Mac and Windows, find out the IP address of your machine:

```console
docker-machine ip default
```

This will provide the IP address associated with the Docker Machine created by Toolbox.

For Linux, Docker host is running on local machine and so the IP address would be `127.0.0.1`.

Edit `/etc/hosts` (Mac OS or Linux) or `C:\Windows\System32\drivers\etc\hosts` (Windows) and add:

[source, text]
----
<IP ADDRESS>  dockerhost
----

=== Pre-requisites

This tutorial uses a few Docker images and software. Let's download them before we start the tutorial.

==== Pull Docker images

Download the Docker images.

IMPORTANT: For Mac and Windows, this commands need to be issued from the Docker shell or Command Prompt where `eval $(docker-machine env default)` command was issued.

Create a new file, name it `docker-compose-pull-images.yml`, and add the following content:

[source, text]
----
ubuntu:
  image: ubuntu
busybox:
  image: busybox
java:
  image: java
tomee:
  image: tomee
wildfly:
  image: jboss/wildfly
mysql:
  image: mysql
javaee7-hol:
  image: arungupta/javaee7-hol
swarm:
  image: swarm
wildfly-couchbase-javaee7:
  image: arungupta/wildfly-couchbase-javaee7
couchbase:
  image: arungupta/couchbase
----

Give the command to pull all the images:

```console
docker-compose -f docker-compose-pull-images.yml pull
```

NOTE: For Linux, `docker-compose` and `docker` commands need `sudo` access. So prefix all commands with `sudo`.

==== Software

. Download http://eclipse.org/[Eclipse IDE for Java EE Developers Mars 2] and install.
. Download https://maven.apache.org/download.cgi[Maven] and install.
. Install Docker CLI following the https://docs.docker.com/docker-cloud/tutorials/installing-cli/[instructions].
