[appendix]
[[Troubleshooting]]

== Troubleshooting Docker

=== Network Timed Out

Depending upon the network speed and restrictions, you may not be able to download Docker images from Docker Store. The error message may look like:

```console
$ docker pull arungupta/wildfly-mysql-javaee7
Using default tag: latest
Pulling repository docker.io/arungupta/wildfly-mysql-javaee7
Network timed out while trying to connect to https://index.docker.io/v1/repositories/arungupta/wildfly-mysql-javaee7/images. You may want to check your internet connection or if you are behind a proxy.
```

This section provide a couple of alternatives to solve this.

==== Restart Docker Machine

It seems like Docker Machine gets into a strange state and restarting it fixes that.

```console
docker-machine restart <MACHINE_NAME>
eval $(docker-machine env <MACHINE_NAME>)
```

=== Cannot create Docker Machine on Windows

Are you not able to create Docker Machine on Windows?

Try starting a `cmd` with Administrator privileges and then give the command again.

=== Docker machine creation fails with an error about dial tcp: i/o timeout

If you get the following error when creating a docker machine

[source, text]
----
Error creating machine: Error in driver during machine creation: Get https://api.github.com/repos/boot2docker/boot2docker/releases: dial tcp: i/o timeout
----

Then you need to go to the boot2docker releases page on

https://github.com/boot2docker/boot2docker/releases

And download the latest .iso

After that you can move that iso to the docker cache directory. This is located in `~/.docker/machine/cache` on Mac & Linux and `/Users/yourUserName/.docker/machine/cache` on Windows.

Issue: https://github.com/docker/machine/issues/2186 is raised so that the docker-machine team can hopefully find a way around this.

=== "`You may be getting rate limited by Github`" error message

Credits: https://github.com/docker/machine/blob/master/README.md#troubleshooting

In order to `create` or `upgrade` virtual machines running Docker, Docker
Machine will check the Github API for the latest release of the [boot2docker
operating system](https://github.com/boot2docker/boot2docker).  The Github API
allows for a small number of unauthenticated requests from a given client, but
if you share an IP address with many other users (e.g. in an office), you may
get rate limited by their API, and Docker Machine will error out with messages
indicating this.

In order to work around this issue, you can https://help.github.com/articles/creating-an-access-token-for-command-line-use/[generate a
token] and pass it to Docker Machine using the global `--github-api-token` flag:

```console
$ docker-machine --github-api-token=token create -d virtualbox newbox
```

This should eliminate any issues you've been experiencing with rate limiting.

=== Docker Machine Troubleshooting

https://github.com/docker/machine/blob/master/README.md#troubleshooting[Docker Machine Troubleshooting] section has good tips on what can possibly go wrong with Docker Machine. Look there if your issue is not explained here.

